// angel-practica-angular/src/app/components/perfil.component/perfil.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ServiceEmpleados } from '../../services/ServicesEmpleados';
import { Empleado } from '../../models/Empleado';

@Component({
  selector: 'app-perfil.component',
  imports:[CommonModule],
  templateUrl: './perfil.component.html',
  styleUrl: './perfil.component.css',
})
export class PerfilComponent implements OnInit{
  public perfil!: Empleado;
  constructor(private _service: ServiceEmpleados) {
  }
  ngOnInit(): void {
  const token = localStorage.getItem("token");
    if (token !== "" && token !== null) {
      this._service.GetPerfilEmpleado(token).subscribe(response => {
        this.perfil = response
      })
    }
  }
}

<div class="card shadow-sm" style="max-width: 400px; margin: 2rem auto;" *ngIf="perfil">
    <div class="card-header bg-primary text-white">
        <h4 class="mb-0">
            <i class="bi bi-person-circle me-2"></i>Perfil del Empleado
        </h4>
    </div>
    <div class="card-body">
        <div class="mb-3">
            <label class="text-muted small">ID Empleado</label>
            <p class="fw-bold">{{ perfil.idEmpleado }}</p>
        </div>
        <div class="mb-3">
            <label class="text-muted small">Apellido</label>
            <p class="fw-bold">{{ perfil.apellido }}</p>
        </div>
        <div class="mb-3">
            <label class="text-muted small">Oficio</label>
            <p class="fw-bold">{{ perfil.oficio }}</p>
        </div>
        <div class="mb-3">
            <label class="text-muted small">Salario</label>
            <p class="fw-bold text-success">{{ perfil.salario | currency:'EUR' }}</p>
        </div>
        <div class="mb-3">
            <label class="text-muted small">Director</label>
            <p class="fw-bold">{{ perfil.director }}</p>
        </div>
    </div>
</div>

// angel-practica-vue/src/components/PerfilComponent.vue
<template>
  <div>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-lg">
                    <div class="card-header bg-primary text-white text-center">
                        <h3><i class="bi bi-person-circle"></i> Perfil de Empleado</h3>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <label class="text-muted fw-bold">ID Empleado</label>
                            <p class="h5">{{ empleado.idEmpleado }}</p>
                        </div>
                        <div class="mb-3">
                            <label class="text-muted fw-bold">Apellido</label>
                            <p class="h5">{{ empleado.apellido }}</p>
                        </div>
                        <div class="mb-3">
                            <label class="text-muted fw-bold">Oficio</label>
                            <p class="h5">{{ empleado.oficio }}</p>
                        </div>
                        <div class="mb-3">
                            <label class="text-muted fw-bold">Salario</label>
                            <p class="h5">{{ empleado.salario }}€</p>
                        </div>
                        <div class="mb-3">
                            <label class="text-muted fw-bold">Director</label>
                            <p class="h5">{{ empleado.director }}</p>
                        </div>
                    </div>
                    <div class="card-footer text-center">
                        <button class="btn btn-secondary" @click="$router.push('/')">
                            <i class="bi bi-arrow-left"></i> Volver
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</template>

<script>
import ServiceEmpleados from '../services/ServiceEmpleados'
const service = new ServiceEmpleados();
export default {
    name:"PerfilComponent",
    data() {
        return {
            empleado: []
        }
    },
    mounted () {
        const token = localStorage.getItem("token")
        if(token !== null && token !== ""){
            service.getPerfil(token).then(response => {
                this.empleado = response
            })
        }   
    },
}
</script>

<style>

</style>
