// angel-practica-vue/src/components/LoginComponent.vue
<template>
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body p-4">
                    <h3 class="card-title text-center mb-4">Iniciar Sesión</h3>
                    <form >
                        <div class="mb-3">
                            <label for="user" class="form-label">Usuario</label>
                            <input 
                                v-model="user" 
                                type="text" 
                                class="form-control" 
                            />
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Contraseña</label>
                            <input 
                                v-model="password" 
                                type="password" 
                                class="form-control" 
                            />
                        </div>
                        <div class="d-grid">
                            <button @click.prevent="Login()" class="btn btn-primary">
                                Iniciar Sesión
                            </button>
                        </div>
                    </form>
                    <p class="mt-3 text-danger" v-if="error">{{ error }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
</template>

<script>
import ServiceEmpelados from '../services/ServiceEmpleados'
const service = new ServiceEmpelados()
export default {
    name:"LoginComponent",
    data() {
        return {
            user: "",
            password: "",
            error: ""
        }
    },
    methods: {
        Login() {
            service.getToken(this.user,this.password).then(response =>{
                localStorage.setItem("token",response)
                this.$router.push("/perfil")
            }).catch(() => {
                this.error = "Usuario o contraseña incorrectos"
            })
        }
    },
}
</script>

<style>

</style>

// angel-practica-angular/src/app/components/login.component/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ServiceEmpleados } from '../../services/ServicesEmpleados';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login.component',
  imports: [FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent implements OnInit{
  public user: string = "Rey";
  public password: string = "7839";
  
  constructor(
    private _service: ServiceEmpleados,
    private _router: Router
  ) {}
  Login():void{
    this._service.Login(this.user,this.password).subscribe(response => {
      localStorage.setItem("token",response.response)
      this._router.navigate(["/perfil"])
    })
  }
  ngOnInit(): void {
    
  }
}

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body p-4">
                    <h3 class="card-title text-center mb-4">Iniciar Sesión</h3>
                    <form (ngSubmit)="Login()" #form="ngForm">
                        <div class="mb-3">
                            <label for="user" class="form-label">Usuario</label>
                            <input 
                                type="text" 
                                class="form-control" 
                                name="user"
                                [(ngModel)]="user"
                            />
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Contraseña</label>
                            <input 
                                type="password" 
                                class="form-control" 
                                name="password"
                                [(ngModel)]="password"
                            />
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary">
                                Iniciar Sesión
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
